include: package:lint/analysis_options_package.yaml

linter:
  rules:
    use_setters_to_change_properties: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false